# Generated by Django 2.2.1 on 2019-06-16 20:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dict',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=100)),
                ('pron', models.CharField(blank=True, max_length=100, null=True)),
                ('morf', models.CharField(blank=True, max_length=100, null=True)),
                ('trans', models.TextField(blank=True, null=True)),
                ('phrase', models.TextField(blank=True, null=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('added', models.BooleanField(default=False)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dict', to=settings.AUTH_USER_MODEL, verbose_name='Added by')),
            ],
        ),
    ]
