# Generated by Django 2.2.1 on 2019-06-17 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myserver', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dict',
            name='form',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
