# Generated by Django 2.2.1 on 2019-06-17 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myserver', '0002_dict_form'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dict',
            name='phrase',
        ),
    ]
