# Generated by Django 2.2.1 on 2019-06-17 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myserver', '0004_auto_20190617_1113'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dict',
            name='added',
        ),
        migrations.AddField(
            model_name='dict',
            name='label',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
