# Generated by Django 2.2.1 on 2019-06-17 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myserver', '0005_auto_20190617_1410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dict',
            name='forms',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
