# Generated by Django 2.2.1 on 2019-06-20 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myserver', '0006_auto_20190617_1452'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dict',
            old_name='label',
            new_name='name_label',
        ),
        migrations.AddField(
            model_name='dict',
            name='last_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='dict',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
