# Generated by Django 2.2.1 on 2019-06-21 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myserver', '0007_auto_20190620_1715'),
    ]

    operations = [
        migrations.AddField(
            model_name='dict',
            name='accordion_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='dict',
            name='collapse_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='dict',
            name='heading_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
