# Generated by Django 2.2.1 on 2019-06-22 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myserver', '0009_dict_last_name_date_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dict',
            name='name_label',
            field=models.TextField(blank=True, default='', help_text='Name label', null=True),
        ),
    ]
