# Generated by Django 2.2.1 on 2019-06-22 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myserver', '0011_auto_20190622_1308'),
    ]

    operations = [
        migrations.AddField(
            model_name='dict',
            name='word_user',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='dict',
            name='accordion_id',
            field=models.CharField(blank=True, default='', help_text='Format: accordion_word &nbsp;&nbsp;&nbsp;Example: accordion_jag', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='dict',
            name='collapse_id',
            field=models.CharField(blank=True, default='', help_text='Format: collapse_word &nbsp;&nbsp;&nbsp;Example: collapse_jag', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='dict',
            name='heading_id',
            field=models.CharField(blank=True, default='', help_text='Format: heading_word &nbsp;&nbsp;&nbsp;Example: heading_jag', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='dict',
            name='last_name_date_label',
            field=models.TextField(blank=True, default='', help_text='Format: username1_date;username2_date; &nbsp;&nbsp;&nbsp;Example: testuser_20190622;', null=True),
        ),
        migrations.AlterField(
            model_name='dict',
            name='name_label',
            field=models.TextField(blank=True, default='', help_text='Format: username1;username2; &nbsp;&nbsp;&nbsp;Example: testuser;', null=True),
        ),
    ]
