# Generated by Django 2.2.1 on 2019-06-24 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myserver', '0012_auto_20190622_2107'),
    ]

    operations = [
        migrations.AddField(
            model_name='dict',
            name='word_forms',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
