# Generated by Django 2.2.1 on 2019-06-24 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myserver', '0013_dict_word_forms'),
    ]

    operations = [
        migrations.AddField(
            model_name='dict',
            name='trans_all',
            field=models.TextField(blank=True, help_text='For more detailed display in card view and detail view.', null=True),
        ),
        migrations.AlterField(
            model_name='dict',
            name='trans',
            field=models.TextField(blank=True, help_text='For concise display in table view.', null=True),
        ),
        migrations.AlterField(
            model_name='dict',
            name='word',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='dict',
            name='word_forms',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='dict',
            name='word_user',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
