# Generated by Django 2.2.1 on 2019-06-24 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myserver', '0014_auto_20190624_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dict',
            name='trans_all',
            field=models.TextField(blank=True, default='', help_text='For more detailed display in card view and detail view.', null=True),
        ),
    ]
