# Generated by Django 2.2.1 on 2019-06-25 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myserver', '0015_auto_20190624_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dict',
            name='morf',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='dict',
            name='pron',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
