# Generated by Django 2.2.1 on 2019-06-26 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myserver', '0016_auto_20190625_1719'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dict',
            name='added_by',
        ),
    ]
