# Generated by Django 2.2.1 on 2019-06-12 15:24

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('deep', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Module',
            new_name='Deep',
        ),
        migrations.AlterModelOptions(
            name='deep',
            options={'permissions': (('can_publish_delete', 'Can publish and delete modules.'),), 'verbose_name_plural': 'Deep Learning'},
        ),
    ]
