# Generated by Django 2.2.1 on 2019-06-19 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deep', '0004_deep_script'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deep',
            name='script',
            field=models.FileField(blank=True, null=True, upload_to='deep/%Y/%m/%d/'),
        ),
    ]
