# Generated by Django 2.2.1 on 2019-06-19 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machine', '0002_machine_usage'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='script',
            field=models.FileField(blank=True, null=True, upload_to='machine/%Y/%m/%d/'),
        ),
    ]
