# Generated by Django 2.2.1 on 2019-06-02 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mypython', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PythonModule',
            new_name='Modules',
        ),
    ]
