# Generated by Django 2.2.1 on 2019-06-02 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mypython', '0002_auto_20190602_1355'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Modules',
            new_name='MyModules',
        ),
    ]
