# Generated by Django 2.2.1 on 2019-06-02 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mypython', '0003_auto_20190602_1403'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MyModules',
            new_name='MyModule',
        ),
    ]
