# Generated by Django 2.2.1 on 2019-06-02 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mypython', '0004_auto_20190602_1409'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MyModule',
            new_name='Module',
        ),
    ]
