# Generated by Django 2.2.1 on 2019-06-02 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mypython', '0008_module_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='module',
            name='slug',
        ),
    ]
