# Generated by Django 2.2.1 on 2019-06-08 20:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mypython', '0009_remove_module_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='module',
            name='submitted',
        ),
        migrations.AddField(
            model_name='module',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='module',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='module',
            name='published_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='module',
            name='slug',
            field=models.SlugField(default='numpy'),
        ),
        migrations.AlterField(
            model_name='module',
            name='type',
            field=models.CharField(choices=[('Python', 'Python General'), ('Django', 'Django'), ('Machine', 'Machine Learning'), ('Deep', 'Deep Learning'), ('Finance', 'Finance'), ('Image', 'Image'), ('Chem', 'Cheoinformatics'), ('Bio', 'Bioinformatics')], max_length=10),
        ),
    ]
