# Generated by Django 2.2.1 on 2019-06-08 21:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mypython', '0011_remove_module_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='module',
            name='author',
        ),
        migrations.AddField(
            model_name='module',
            name='added_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Added by'),
        ),
    ]
