# Generated by Django 2.2.1 on 2019-06-10 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mypython', '0013_auto_20190609_0156'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='code',
            field=models.TextField(default='Python code'),
            preserve_default=False,
        ),
    ]
