# Generated by Django 2.2.1 on 2019-06-10 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mypython', '0014_module_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='code',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='module',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='module',
            name='reference',
            field=models.URLField(blank=True, null=True),
        ),
    ]
