# Generated by Django 2.2.1 on 2019-06-12 16:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mypython', '0016_auto_20190612_1603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='added_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='python', to=settings.AUTH_USER_MODEL, verbose_name='Added by'),
        ),
    ]
