# Generated by Django 2.2.1 on 2019-06-20 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mypython', '0019_module_script'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='script',
            field=models.FileField(blank=True, null=True, upload_to='mypython/%Y/%m/%d/'),
        ),
    ]
